### ISSUE TITLE
[BUG] Crash on command formatting when deleting a character

### ISSUE THREAD

**Issue by Pablete1234** [DarkKronicle/AdvancedChatBox#2]
**Describe the bug**
Minecraft crashes when deleting the first character in `a/aaa` in chat

**Minecraft Info**
Minecraft information:
```
---- Minecraft Crash Report ----
// My bad.

Time: 8/11/21 1:40
Description: Rendering screen

java.lang.StringIndexOutOfBoundsException: begin 4, end 6, length 5
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
    at java.base/java.lang.String.substring(String.java:1907)
    at java.base/java.lang.String.subSequence(String.java:1945)
    at io.github.darkkronicle.advancedchatbox.chat.ChatFormatter.format(ChatFormatter.java:61)
    at io.github.darkkronicle.advancedchatbox.chat.ChatFormatter.apply(ChatFormatter.java:117)
    at io.github.darkkronicle.advancedchatbox.chat.ChatSuggestorGui.provideRenderText(ChatSuggestorGui.java:333)
    at net.minecraft.class_342.method_25359(class_342.java:426)
    at net.minecraft.class_339.method_25394(class_339.java:67)
    at io.github.darkkronicle.advancedchatcore.chat.AdvancedChatScreen.method_25394(AdvancedChatScreen.java:290)
    at net.minecraft.class_757.method_3192(class_757.java:874)
    at net.minecraft.class_310.method_1523(class_310.java:1112)
    at net.minecraft.class_310.method_1514(class_310.java:728)
    at net.minecraft.client.main.Main.main(Main.java:217)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**To Reproduce**
1. Open chat
2. type `a/aaaa` or really any letter followed by a command
3. put your cursor at the very start of the message
4. press delete, which removes the first character

**Expected behavior**
Minecraft not to crash

**Comment by DarkKronicle** [comment]
This will be fixed next update
